analyzer:
  exclude:
    - build/**
  language:
    strict-casts: true
    strict-inference: true
  errors:
    avoid_print: warning
    dead_code: warning

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - use_key_in_widget_constructors
