name: sipsva
description: Interfaz móvil del Sistema Inteligente Preventivo de Señalización Vial Adaptativa.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_bluetooth: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
